### ISSUE TITLE
The CHAR type of ORC supports the problem

### ISSUE THREAD

**Issue by rhh777** [oap-project/velox#455]
### Bug description

Is the CHAR type of ORC currently not supported?

Gluten:1.1.0

### System information

Caused by: java.lang.RuntimeException: Exception: VeloxRuntimeError
Error Source: RUNTIME
Error Code: INVALID_STATE
Reason: CHAR not supported yet.
Retriable: False
Context: Split [Hive: hdfs://sparkHa/warehouse/tablespace/managed/hive/tpcds_bin_partitioned_orc_100.db/customer/000085_0 0 - 886854] Task Gluten_Stage_2_TID_2067
Top-Level Context: Same as context.
Function: kind
File: /root/src/oap-project/gluten/ep/build-velox/build/velox_ep/velox/dwio/dwrf/common/FileMetadata.cpp
Line: 105
Stack trace:
 0  _ZN8facebook5velox7process10StackTraceC1Ei
 1  _ZN8facebook5velox14VeloxExceptionC1EPKcmS3_St17basic_string_viewIcSt11char_traitsIcEES7_S7_S7_bNS1_4TypeES7_
 2  _ZN8facebook5velox6detail14veloxCheckFailINS0_17VeloxRuntimeErrorERKSsEEvRKNS1_18VeloxCheckFailArgsET0_
 3  _ZNK8facebook5velox4dwrf11TypeWrapper4kindEv
 4  _ZN8facebook5velox4dwrf10ReaderBase11convertTypeERKNS1_13FooterWrapperEjb
 5  _ZN8facebook5velox4dwrf10ReaderBase11convertTypeERKNS1_13FooterWrapperEjb
 6  _ZN8facebook5velox4dwrf10ReaderBaseC2ERNS0_6memory10MemoryPoolESt10unique_ptrINS0_4dwio6common13BufferedInputESt14default_deleteIS9_EESt10shared_ptrINS8_10encryption16DecrypterFactoryEEmmNS8_10FileFormatEb
 7  _ZN8facebook5velox4dwrf10DwrfReaderC1ERKNS0_4dwio6common13ReaderOptionsESt10unique_ptrINS4_13BufferedInputESt14default_deleteIS9_EE
 8  _ZN8facebook5velox4dwrf10DwrfReader6createESt10unique_ptrINS0_4dwio6common13BufferedInputESt14default_deleteIS6_EERKNS5_13ReaderOptionsE
 9  _ZN8facebook5velox4dwrf16OrcReaderFactory12createReaderESt10unique_ptrINS0_4dwio6common13BufferedInputESt14default_deleteIS6_EERKNS5_13ReaderOptionsE
 10 _ZN8facebook5velox9connector4hive11SplitReader12prepareSplitERKSt10shared_ptrINS2_15HiveTableHandleEERKNS0_4dwio6common13ReaderOptionsESt10unique_ptrINSA_13BufferedInputESt14default_deleteISF_EES4_INS0_6common14MetadataFilterEERNSA_17RuntimeStatisticsE
 11 _ZN8facebook5velox9connector4hive14HiveDataSource8addSplitESt10shared_ptrINS1_14ConnectorSplitEE
 12 _ZN8facebook5velox4exec9TableScan9getOutputEv
 13 _ZN8facebook5velox4exec6Driver11runInternalERSt10shared_ptrIS2_ERS3_INS1_13BlockingStateEERS3_INS0_9RowVectorEE
 14 _ZN8facebook5velox4exec6Driver4nextERSt10shared_ptrINS1_13BlockingStateEE
 15 _ZN8facebook5velox4exec4Task4nextEPN5folly10SemiFutureINS3_4UnitEEE
 16 _ZN6gluten24WholeStageResultIterator4nextEv
 17 Java_io_glutenproject_vectorized_ColumnarBatchOutIterator_nativeHasNext
 18 0x00007fc899018427
        at io.glutenproject.vectorized.ColumnarBatchOutIterator.nativeHasNext(Native Method)
        at io.glutenproject.vectorized.ColumnarBatchOutIterator.hasNextInternal(ColumnarBatchOutIterator.java:65)
        at io.glutenproject.vectorized.GeneralOutIterator.hasNext(GeneralOutIterator.java:37)
        ... 20 more

**Comment by rhh777** [comment]
Is there any plan to support it in the near future?
