### ISSUE TITLE
`hive.s3.endpoint` is not set correctly by gluten

### ISSUE THREAD

**Issue by dcoliversun** [oap-project/velox#464]
### Bug description

I test native write to Alibaba OSS with gluten + velox. Spark configuration is here
```plain
spark.hadoop.fs.s3a.endpoint: https://oss-cn-hangzhou.aliyuncs.com
spark.hadoop.fs.s3a.access.key: <access-key>
spark.hadoop.fs.s3a.secret.key: <secret-key>
spark.hadoop.fs.s3a.path.style.access: false
spark.hadoop.fs.s3a.connection.ssl.enabled: true
```
But aws-cpp-sdk wants to visit `s3.us-east-1.amazonaws.com` 
[aws_sdk_2023-12-18-08.log](https://github.com/oap-project/velox/files/13701995/aws_sdk_2023-12-18-08.log)

### System information

Velox System Info v0.0.2
Commit: c7389f1a819a3ce18a319fae1b7dcbee24d53f6d
CMake Version: 3.22.1
System: Linux-6.5.11-linuxkit
Arch: x86_64
C++ Compiler: /usr/bin/c++
C++ Compiler Version: 11.4.0
C Compiler: /usr/bin/cc
C Compiler Version: 11.4.0
CMake Prefix Path: /usr/local;/usr;/;/usr;/usr/local;/usr/X11R6;/usr/pkg;/opt

### Relevant logs

```bash
gluten commit is fcdd30e582df12275c66275e3a1dc956a193a324
```

**Comment by dcoliversun** [comment]
@zhouyuan Could you please check this issue? I also submit a ticket in facebook repo https://github.com/facebookincubator/velox/issues/8013

**Comment by dcoliversun** [comment]
Got more log with `spark.gluten.sql.debug=true`
```plain
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
WARNING: Logging before InitGoogleLogging() is written to STDERR
I1218 04:42:57.058038 77757 VeloxBackend.cc:142] VeloxBackend config:
 [spark.hadoop.dfs.client.log.severity, INFO]
 [spark.hadoop.input.write.timeout, 180000]
 [spark.hadoop.fs.s3a.impl, org.apache.hadoop.fs.s3a.S3AFileSystem]
 [spark.hadoop.input.connect.timeout, 180000]
 [spark.memory.offHeap.enabled, true]
 [spark.gluten.velox.awsSdkLogLevel, FATAL]
 [spark.gluten.sql.debug, true]
 [spark.hadoop.fs.s3a.iam.role.session.name, ]
 [spark.sql.orc.compression.codec, snappy]
 [spark.hadoop.fs.s3a.iam.role, ]
 [spark.gluten.memory.offHeap.size.in.bytes, 1048576000]
 [spark.gluten.sql.columnar.backend.velox.fileHandleCacheEnabled, false]
 [spark.gluten.sql.columnar.backend.velox.IOThreads, 0]
 [spark.hadoop.fs.s3a.use.instance.credentials, false]
 [spark.hadoop.fs.s3a.secret.key, <secret-key>]
 [spark.hadoop.fs.s3a.connection.ssl.enabled, true]
 [spark.hadoop.fs.s3a.access.key, <access-key>]
 [spark.gluten.memory.task.offHeap.size.in.bytes, 174762666]
 [spark.hadoop.fs.s3a.path.style.access, false]
 [spark.gluten.sql.columnar.shuffle.codec, ]
 [spark.hadoop.fs.s3a.aws.credentials.provider, org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider]
 [spark.hadoop.input.read.timeout, 180000]
 [spark.hadoop.fs.s3a.endpoint, https://oss-cn-hangzhou.aliyuncs.com]
 [spark.gluten.sql.columnar.shuffle.codecBackend, ]
 [spark.gluten.sql.columnar.backend.velox.SplitPreloadPerDriver, 2]
I1218 04:42:57.058226 77757 HiveConnector.cpp:70] Hive connector test-hive created with file handle cache disabled
Spark context Web UI available at http://c1b9eea6625f:4040
```


```plain
23/12/18 04:44:12 WARN ObjectStore: Failed to get database global_temp, returning NoSuchObjectException
[libprotobuf WARNING google/protobuf/util/internal/json_objectwriter.cc:52] JsonObjectWriter was not fully closed.
W1218 04:44:13.640640 77757 VeloxJniWrapper.cc:101] Error converting Substrait plan for validation to JSON: BinaryToJsonStream returned INTERNAL:Invalid type URL, type URLs must be of the form '/<typename>', got: type.googleapis.com/substrait.Type
23/12/18 04:44:14 WARN SessionState: METASTORE_FILTER_HOOK will be ignored, since hive.security.authorization.manager is set to instance of HiveAuthorizerFactory.
23/12/18 04:44:14 WARN HiveConf: HiveConf of name hive.internal.ss.authz.settings.applied.marker does not exist
23/12/18 04:44:14 WARN HiveConf: HiveConf of name hive.stats.jdbc.timeout does not exist
23/12/18 04:44:14 WARN HiveConf: HiveConf of name hive.stats.retries.wait does not exist
I1218 04:44:18.043102 77885 VeloxRuntime.cc:43] ################################################## received substrait::Plan:
I1218 04:44:18.043154 77885 VeloxRuntime.cc:44] [Stage: 0 TID: 0]
{"relations":[{"root":{"input":{"project":{"common":{"emit":{"outputMapping":[1,2,3]}},"input":{"read":{"baseSchema":{"names":["fake_column#20"],"struct":{"types":[{"string":{"nullability":"NULLABILITY_NULLABLE"}}]}},"localFiles":{"items":[{"uriFile":"iterator:0"}]}}},"expressions":[{"literal":{"i32":1}},{"literal":{"i32":1}},{"literal":{"i32":10}}]}},"names":["a#11","b#18","c#19"]}}]}
I1218 04:44:18.043211 77885 VeloxRuntime.cc:88] VeloxRuntime session config:
 [spark.gluten.memory.task.offHeap.size.in.bytes, 174762666]
 [spark.gluten.ugi.username, root]
 [spark.sql.caseSensitive, false]
 [spark.gluten.ugi.tokens, ]
 [spark.gluten.sql.debug, true]
 [spark.gluten.sql.session.timeZone.default, America/New_York]
I1218 04:44:18.044122 77885 FileSystems.cpp:161] LocalFileSystem::mkdir /tmp/gluten-c18fb0cf-15f7-4a99-b5ee-dd68ca5867d0/gluten-spill/0c3b8ef0-6f3a-41f6-b302-6693e317a099
E1218 04:44:30.811352 77885 Exceptions.h:69] Line: /gluten/ep/build-velox/build/velox_ep/velox/connectors/hive/storage_adapters/s3fs/S3FileSystem.cpp:242, Function:Impl, Expression:  Failed to create S3 bucket due to: 'Access denied'. Path:'s3://henghzhen-test-hangzhou/', SDK Error Type:15, HTTP Status Code:403, S3 Service:'AmazonS3', Message:'Access Denied', RequestID:'QCQGWJKGJP9DZHEH', Source: RUNTIME, ErrorCode: INVALID_STATE
23/12/18 04:44:30 ERROR Utils: Aborting task
java.lang.RuntimeException: Exception: VeloxRuntimeError
Error Source: RUNTIME
Error Code: INVALID_STATE
Reason: Failed to create S3 bucket due to: 'Access denied'. Path:'s3://henghzhen-test-hangzhou/', SDK Error Type:15, HTTP Status Code:403, S3 Service:'AmazonS3', Message:'Access Denied', RequestID:'QCQGWJKGJP9DZHEH'
Retriable: False
Function: Impl
File: /gluten/ep/build-velox/build/velox_ep/velox/connectors/hive/storage_adapters/s3fs/S3FileSystem.cpp
Line: 242
Stack trace:
# 0  facebook::velox::VeloxException::VeloxException(char const*, unsigned long, char const*, std::basic_string_view<char, std::char_traits<char> >, std::basic_string_view<char, std::char_traits<char> >, std::basic_string_view<char, std::char_traits<char> >, std::basic_string_view<char, std::char_traits<char> >, bool, facebook::velox::VeloxException::Type, std::basic_string_view<char, std::char_traits<char> >)
# 1  void facebook::velox::detail::veloxCheckFail<facebook::velox::VeloxRuntimeError, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>(facebook::velox::detail::VeloxCheckFailArgs const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
# 2  facebook::velox::filesystems::S3WriteFile::Impl::Impl(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Aws::S3::S3Client*, facebook::velox::memory::MemoryPool*)
# 3  facebook::velox::filesystems::S3WriteFile::S3WriteFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Aws::S3::S3Client*, facebook::velox::memory::MemoryPool*)
# 4  facebook::velox::filesystems::S3FileSystem::openFileForWrite(std::basic_string_view<char, std::char_traits<char> >, facebook::velox::filesystems::FileOptions const&)
# 5  gluten::VeloxParquetDatasource::init(std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&)
# 6  Java_io_glutenproject_datasource_DatasourceJniWrapper_nativeInitDatasource
# 7  0x00007fbe91018426
# 8  0x00007fbe91007b0f
# 9  0x00007fbe91007b0f
# 10 0x00007fbe91007d7f
# 11 0x00007fbe91007d7f
# 12 0x00007fbe91007e53
# 13 0x00007fbe91007d7f
# 14 0x00007fbe91007ffc
# 15 0x00007fbe91007ffc
# 16 0x00007fbe91007ffc
# 17 0x00007fbe91007ffc
# 18 0x00007fbe91007ffc
# 19 0x00007fbe91007d7f
# 20 0x00007fbe91007e53
# 21 0x00007fbe91007d7f
# 22 0x00007fbe91007d7f
# 23 0x00007fbe91007d7f
# 24 0x00007fbe91007e53
# 25 0x00007fbe91007d7f
# 26 0x00007fbe91007d7f
# 27 0x00007fbe91007d7f
# 28 0x00007fbe91007e53
# 29 0x00007fbe91007d7f
# 30 0x00007fbe91008041
# 31 0x00007fbe91007ffc
# 32 0x00007fbe91008041
# 33 0x00007fbe910004e6
# 34 0x0000000000000000
# 35 0x0000000000000000
# 36 0x0000000000000000
# 37 0x0000000000000000
# 38 0x0000000000000000
# 39 0x0000000000000000
# 40 0x0000000000000000
# 41 0x0000000000000000

	at io.glutenproject.datasource.DatasourceJniWrapper.nativeInitDatasource(Native Method)
	at io.glutenproject.datasource.DatasourceJniWrapper.nativeInitDatasource(DatasourceJniWrapper.java:49)
	at org.apache.spark.sql.execution.datasources.velox.VeloxFormatWriterInjects.createOutputWriter(VeloxFormatWriterInjects.scala:70)
	at org.apache.spark.sql.execution.datasources.velox.VeloxFormatWriterInjects.createOutputWriter$(VeloxFormatWriterInjects.scala:43)
	at org.apache.spark.sql.execution.datasources.velox.VeloxParquetWriterInjects.createOutputWriter(VeloxParquetWriterInjects.scala:26)
	at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat$$anon$1.newInstance(ParquetFileFormat.scala:108)
	at org.apache.spark.sql.execution.datasources.BaseDynamicPartitionDataWriter.renewCurrentWriter(FileFormatDataWriter.scala:311)
	at org.apache.spark.sql.execution.datasources.DynamicPartitionDataSingleWriter.beforeWrite(FileFormatDataWriter.scala:398)
	at org.apache.spark.sql.execution.datasources.DynamicPartitionDataSingleWriter.write(FileFormatDataWriter.scala:418)
	at org.apache.spark.sql.execution.datasources.FileFormatDataWriter.writeWithMetrics(FileFormatDataWriter.scala:96)
	at org.apache.spark.sql.execution.datasources.FileFormatDataWriter.writeWithIterator(FileFormatDataWriter.scala:103)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.$anonfun$executeTask$1(FileFormatWriter.scala:414)
	at org.apache.spark.util.Utils$.tryWithSafeFinallyAndFailureCallbacks(Utils.scala:1525)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.executeTask(FileFormatWriter.scala:423)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.$anonfun$write$17(FileFormatWriter.scala:331)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:131)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:506)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1491)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:509)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
23/12/18 04:44:30 ERROR TaskResources: Task 0 failed by error: 
java.lang.RuntimeException: Exception: VeloxRuntimeError
Error Source: RUNTIME
Error Code: INVALID_STATE
Reason: Failed to create S3 bucket due to: 'Access denied'. Path:'s3://henghzhen-test-hangzhou/', SDK Error Type:15, HTTP Status Code:403, S3 Service:'AmazonS3', Message:'Access Denied', RequestID:'QCQGWJKGJP9DZHEH'
Retriable: False
Function: Impl
File: /gluten/ep/build-velox/build/velox_ep/velox/connectors/hive/storage_adapters/s3fs/S3FileSystem.cpp
Line: 242
Stack trace:
# 0  facebook::velox::VeloxException::VeloxException(char const*, unsigned long, char const*, std::basic_string_view<char, std::char_traits<char> >, std::basic_string_view<char, std::char_traits<char> >, std::basic_string_view<char, std::char_traits<char> >, std::basic_string_view<char, std::char_traits<char> >, bool, facebook::velox::VeloxException::Type, std::basic_string_view<char, std::char_traits<char> >)
# 1  void facebook::velox::detail::veloxCheckFail<facebook::velox::VeloxRuntimeError, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>(facebook::velox::detail::VeloxCheckFailArgs const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
# 2  facebook::velox::filesystems::S3WriteFile::Impl::Impl(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Aws::S3::S3Client*, facebook::velox::memory::MemoryPool*)
# 3  facebook::velox::filesystems::S3WriteFile::S3WriteFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Aws::S3::S3Client*, facebook::velox::memory::MemoryPool*)
# 4  facebook::velox::filesystems::S3FileSystem::openFileForWrite(std::basic_string_view<char, std::char_traits<char> >, facebook::velox::filesystems::FileOptions const&)
# 5  gluten::VeloxParquetDatasource::init(std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&)
# 6  Java_io_glutenproject_datasource_DatasourceJniWrapper_nativeInitDatasource
# 7  0x00007fbe91018426
# 8  0x00007fbe91007b0f
# 9  0x00007fbe91007b0f
# 10 0x00007fbe91007d7f
# 11 0x00007fbe91007d7f
# 12 0x00007fbe91007e53
# 13 0x00007fbe91007d7f
# 14 0x00007fbe91007ffc
# 15 0x00007fbe91007ffc
# 16 0x00007fbe91007ffc
# 17 0x00007fbe91007ffc
# 18 0x00007fbe91007ffc
# 19 0x00007fbe91007d7f
# 20 0x00007fbe91007e53
# 21 0x00007fbe91007d7f
# 22 0x00007fbe91007d7f
# 23 0x00007fbe91007d7f
# 24 0x00007fbe91007e53
# 25 0x00007fbe91007d7f
# 26 0x00007fbe91007d7f
# 27 0x00007fbe91007d7f
# 28 0x00007fbe91007e53
# 29 0x00007fbe91007d7f
# 30 0x00007fbe91008041
# 31 0x00007fbe91007ffc
# 32 0x00007fbe91008041
# 33 0x00007fbe910004e6
# 34 0x0000000000000000
# 35 0x0000000000000000
# 36 0x0000000000000000
# 37 0x0000000000000000
# 38 0x0000000000000000
# 39 0x0000000000000000
# 40 0x0000000000000000
# 41 0x0000000000000000

	at io.glutenproject.datasource.DatasourceJniWrapper.nativeInitDatasource(Native Method)
	at io.glutenproject.datasource.DatasourceJniWrapper.nativeInitDatasource(DatasourceJniWrapper.java:49)
	at org.apache.spark.sql.execution.datasources.velox.VeloxFormatWriterInjects.createOutputWriter(VeloxFormatWriterInjects.scala:70)
	at org.apache.spark.sql.execution.datasources.velox.VeloxFormatWriterInjects.createOutputWriter$(VeloxFormatWriterInjects.scala:43)
	at org.apache.spark.sql.execution.datasources.velox.VeloxParquetWriterInjects.createOutputWriter(VeloxParquetWriterInjects.scala:26)
	at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat$$anon$1.newInstance(ParquetFileFormat.scala:108)
	at org.apache.spark.sql.execution.datasources.BaseDynamicPartitionDataWriter.renewCurrentWriter(FileFormatDataWriter.scala:311)
	at org.apache.spark.sql.execution.datasources.DynamicPartitionDataSingleWriter.beforeWrite(FileFormatDataWriter.scala:398)
	at org.apache.spark.sql.execution.datasources.DynamicPartitionDataSingleWriter.write(FileFormatDataWriter.scala:418)
	at org.apache.spark.sql.execution.datasources.FileFormatDataWriter.writeWithMetrics(FileFormatDataWriter.scala:96)
	at org.apache.spark.sql.execution.datasources.FileFormatDataWriter.writeWithIterator(FileFormatDataWriter.scala:103)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.$anonfun$executeTask$1(FileFormatWriter.scala:414)
	at org.apache.spark.util.Utils$.tryWithSafeFinallyAndFailureCallbacks(Utils.scala:1525)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.executeTask(FileFormatWriter.scala:423)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.$anonfun$write$17(FileFormatWriter.scala:331)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:131)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:506)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1491)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:509)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

**Comment by dcoliversun** [comment]
cc @yma11 correct me if I am wrong
Seem like 
https://github.com/oap-project/gluten/blob/main/cpp/velox/operators/writer/VeloxParquetDatasource.cc#L52
doesn't push configuration to velox? 

Velox usage is https://github.com/facebookincubator/velox/blob/afaaef30b06fea83b7a58055ae7cdb001de1c6ef/velox/connectors/hive/storage_adapters/s3fs/tests/S3FileSystemRegistrationTest.cpp#L56C30-L56C43

**Comment by yma11** [comment]
@dcoliversun Thanks for your info!

The configuration for S3 is used when register the HiveConnector [here](https://github.com/oap-project/gluten/blob/main/cpp/velox/compute/VeloxBackend.cc#L378), but we don't test simple credentials because of env limitation so there may be some problem here. Can you help take a further look?

**Comment by dcoliversun** [comment]
I write hard code to set hiveConfig in VeloxParquetDatasource.cc
```cc
std::unordered_map<std::string, std::string> config({
        {"hive.s3.aws-access-key", accessKey_},
        {"hive.s3.aws-secret-key", secretKey_},
        {"hive.s3.endpoint", connectionString_},
        {"hive.s3.ssl.enabled", "true"},
        {"hive.s3.path-style-access", "false"},
    });
    auto hiveConfig = std::make_shared<const velox::core::MemConfig>(std::move(config))
    auto fileSystem = getFileSystem(filePath_, hiveConfig);
```
It works as expected. I think we have three work to do: 
1. support oss scheme in native write, because velox supoorts[1]
2. Extract the veloxcfg initialization[2] function for use by VeloxParquetDatasource.cc
3. support minio in native write suite[3]

[1] https://facebookincubator.github.io/velox/develop/connectors.html?highlight=oss
[2] https://github.com/oap-project/gluten/blob/main/cpp/velox/compute/VeloxBackend.cc#L269-L373
[3] https://github.com/oap-project/gluten/blob/main/backends-velox/src/test/scala/org/apache/spark/sql/execution/VeloxParquetWriteSuite.scala

I am looking forward to your suggestion :) @yma11  If we agree about these, I will submit three tickets, please assign to me
